driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1024
  network:
    - - forwarded_port
      - guest: 5050
        host: 5050
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared
  data_bags_path: test/integration/default/data_bags

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[zookeeper-apt]
  - name: ubuntu-13.10
    run_list:
      - recipe[apt]
      - recipe[zookeeper-apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[zookeeper-apt]
  - name: debian-7.7
    run_list:
      - recipe[apt]
      - recipe[zookeeper-apt]
  - name: centos-6.5
    run_list:
      - recipe[yum::default]
      - recipe[zookeeper-yum]
  - name: centos-6.4
    run_list:
      - recipe[yum::default]
      - recipe[zookeeper-yum]

suites:
- name: default
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.21.1'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          checkpoint: true
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'

- name: attributes
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  provisioner:
    name: chef_zero
    require_chef_omnibus: 11.12.4
  attributes:
    mesos:
      version: '0.21.1'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
      slave:
        flags:
          attributes:
            test: 'test_value'
          resources:
            cpu:   '24'
            ports: '[21000-24000]'
            bugs:  '{a,b,c}'

- name: 0-22-0
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.22.0'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'

- name: 0-22-1
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.22.1'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'

- name: 0-21-0
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.21.0'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          checkpoint: true
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'

- name: 0-20-1
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.20.1'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          checkpoint: true
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'

- name: 0-20-0
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
  attributes:
    mesos:
      version: '0.20.0'
      master:
        flags:
          authenticate: no
          authenticate_slaves: false
          logging_level: INFO
          cluster: 'MyMesosCluster'
          zk: 'zk://127.0.0.1:2181/mesos'
          quorum: 1
      slave:
        flags:
          gc_delay: 1days
          checkpoint: true
          switch_user: yes
          master: 'zk://127.0.0.1:2181/mesos'
