driver:
  name: vagrant
  customize:
    cpus:     1
    memory:   1024
    nictype1: virtio
  network:
    - ["forwarded_port", {guest: 5050, host: 5050, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: ubuntu-15.04
    run_list:
      - recipe[apt]
      - recipe[curl]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[curl]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[curl]
  - name: debian-8.2
    run_list:
      - recipe[apt]
  - name: centos-7.1
    run_list:
      - recipe[yum]
  - name: centos-6.7
    run_list:
      - recipe[yum]
  - name: box-cutter/ol67
    run_list:
      - recipe[yum]
  - name: box-cutter/ol72
    run_list:
      - recipe[yum]

suites:
- &default
  name: 0-28-0
  attributes:
    mesos:
      slave:
        flags:
          attributes: 'attribute01:value01;attribute02:value02'
  run_list:
    - recipe[mesos::master]
    - recipe[mesos::slave]
- <<: *default
  name: 0-27-2
  attributes:
    mesos:
      version: 0.27.2
- <<: *default
  name: 0-26-0
  attributes:
    mesos:
      version: 0.26.0
